// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rup/v2/envelope.proto

package rupv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signature is one Ed25519 signature over Envelope.payload bytes.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Alg           string                 `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"` // must be "ed25519"
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"` // raw 64-byte signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_rup_v2_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_rup_v2_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Signature) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Signature) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Signature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// Envelope wraps a signed payload on the wire (schema rup.envelope/2).
// payload is the protobuf serialization of Index or Fallback (not JSON).
// The client knows which message to parse from the logical key / URL it fetched.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "rup.envelope/2"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signatures    []*Signature           `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_rup_v2_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_rup_v2_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_rup_v2_envelope_proto protoreflect.FileDescriptor

const file_rup_v2_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15rup/v2/envelope.proto\x12\x06rup.v2\"F\n" +
	"\tSignature\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03alg\x18\x02 \x01(\tR\x03alg\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\"o\n" +
	"\bEnvelope\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x121\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x11.rup.v2.SignatureR\n" +
	"signaturesB\x83\x01\n" +
	"\n" +
	"com.rup.v2B\rEnvelopeProtoP\x01Z-github.com/shichao402/relkit/api/rup/v2;rupv2\xa2\x02\x03RXX\xaa\x02\x06Rup.V2\xca\x02\x06Rup\\V2\xe2\x02\x12Rup\\V2\\GPBMetadata\xea\x02\aRup::V2b\x06proto3"

var (
	file_rup_v2_envelope_proto_rawDescOnce sync.Once
	file_rup_v2_envelope_proto_rawDescData []byte
)

func file_rup_v2_envelope_proto_rawDescGZIP() []byte {
	file_rup_v2_envelope_proto_rawDescOnce.Do(func() {
		file_rup_v2_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rup_v2_envelope_proto_rawDesc), len(file_rup_v2_envelope_proto_rawDesc)))
	})
	return file_rup_v2_envelope_proto_rawDescData
}

var file_rup_v2_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rup_v2_envelope_proto_goTypes = []any{
	(*Signature)(nil), // 0: rup.v2.Signature
	(*Envelope)(nil),  // 1: rup.v2.Envelope
}
var file_rup_v2_envelope_proto_depIdxs = []int32{
	0, // 0: rup.v2.Envelope.signatures:type_name -> rup.v2.Signature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rup_v2_envelope_proto_init() }
func file_rup_v2_envelope_proto_init() {
	if File_rup_v2_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rup_v2_envelope_proto_rawDesc), len(file_rup_v2_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rup_v2_envelope_proto_goTypes,
		DependencyIndexes: file_rup_v2_envelope_proto_depIdxs,
		MessageInfos:      file_rup_v2_envelope_proto_msgTypes,
	}.Build()
	File_rup_v2_envelope_proto = out.File
	file_rup_v2_envelope_proto_goTypes = nil
	file_rup_v2_envelope_proto_depIdxs = nil
}
