// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rup/v2/keys.proto

package rupv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicKeyDocument is the on-disk / embeddable public key record.
type PublicKeyDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // "rup.publickey/2"
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Alg           string                 `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`                              // "ed25519"
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // raw 32-byte ed25519 public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyDocument) Reset() {
	*x = PublicKeyDocument{}
	mi := &file_rup_v2_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyDocument) ProtoMessage() {}

func (x *PublicKeyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyDocument.ProtoReflect.Descriptor instead.
func (*PublicKeyDocument) Descriptor() ([]byte, []int) {
	return file_rup_v2_keys_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyDocument) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PublicKeyDocument) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PublicKeyDocument) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *PublicKeyDocument) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// PrivateKeyDocument is local-only; never publish.
type PrivateKeyDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // "rup.privatekey/2"
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Alg           string                 `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`   // "ed25519"
	Seed          []byte                 `protobuf:"bytes,4,opt,name=seed,proto3" json:"seed,omitempty"` // raw 32-byte seed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKeyDocument) Reset() {
	*x = PrivateKeyDocument{}
	mi := &file_rup_v2_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKeyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKeyDocument) ProtoMessage() {}

func (x *PrivateKeyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKeyDocument.ProtoReflect.Descriptor instead.
func (*PrivateKeyDocument) Descriptor() ([]byte, []int) {
	return file_rup_v2_keys_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateKeyDocument) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PrivateKeyDocument) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PrivateKeyDocument) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *PrivateKeyDocument) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

var File_rup_v2_keys_proto protoreflect.FileDescriptor

const file_rup_v2_keys_proto_rawDesc = "" +
	"\n" +
	"\x11rup/v2/keys.proto\x12\x06rup.v2\"s\n" +
	"\x11PublicKeyDocument\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03alg\x18\x03 \x01(\tR\x03alg\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"i\n" +
	"\x12PrivateKeyDocument\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03alg\x18\x03 \x01(\tR\x03alg\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\fR\x04seedB\x7f\n" +
	"\n" +
	"com.rup.v2B\tKeysProtoP\x01Z-github.com/shichao402/relkit/api/rup/v2;rupv2\xa2\x02\x03RXX\xaa\x02\x06Rup.V2\xca\x02\x06Rup\\V2\xe2\x02\x12Rup\\V2\\GPBMetadata\xea\x02\aRup::V2b\x06proto3"

var (
	file_rup_v2_keys_proto_rawDescOnce sync.Once
	file_rup_v2_keys_proto_rawDescData []byte
)

func file_rup_v2_keys_proto_rawDescGZIP() []byte {
	file_rup_v2_keys_proto_rawDescOnce.Do(func() {
		file_rup_v2_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rup_v2_keys_proto_rawDesc), len(file_rup_v2_keys_proto_rawDesc)))
	})
	return file_rup_v2_keys_proto_rawDescData
}

var file_rup_v2_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rup_v2_keys_proto_goTypes = []any{
	(*PublicKeyDocument)(nil),  // 0: rup.v2.PublicKeyDocument
	(*PrivateKeyDocument)(nil), // 1: rup.v2.PrivateKeyDocument
}
var file_rup_v2_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rup_v2_keys_proto_init() }
func file_rup_v2_keys_proto_init() {
	if File_rup_v2_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rup_v2_keys_proto_rawDesc), len(file_rup_v2_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rup_v2_keys_proto_goTypes,
		DependencyIndexes: file_rup_v2_keys_proto_depIdxs,
		MessageInfos:      file_rup_v2_keys_proto_msgTypes,
	}.Build()
	File_rup_v2_keys_proto = out.File
	file_rup_v2_keys_proto_goTypes = nil
	file_rup_v2_keys_proto_depIdxs = nil
}
