// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rup/v2/objects.proto

package rupv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Selector is one key/value match constraint.
// Signed messages MUST NOT use map<>; encode helpers sort by key before Marshal.
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_rup_v2_objects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{0}
}

func (x *Selector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Selector) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MetaEntry is opaque host-defined metadata (string values only in v2).
type MetaEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaEntry) Reset() {
	*x = MetaEntry{}
	mi := &file_rup_v2_objects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaEntry) ProtoMessage() {}

func (x *MetaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaEntry.ProtoReflect.Descriptor instead.
func (*MetaEntry) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{1}
}

func (x *MetaEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetaEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DigestRef points at immutable bytes with mirrors.
type DigestRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"` // 64 lowercase hex chars
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Urls          []string               `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"` // absolute http(s) URLs, same bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestRef) Reset() {
	*x = DigestRef{}
	mi := &file_rup_v2_objects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestRef) ProtoMessage() {}

func (x *DigestRef) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestRef.ProtoReflect.Descriptor instead.
func (*DigestRef) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{2}
}

func (x *DigestRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DigestRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DigestRef) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// VersionNode is one release in an Index chain.
type VersionNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // display only; never compare
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	MinFrom       int64                  `protobuf:"varint,3,opt,name=min_from,json=minFrom,proto3" json:"min_from,omitempty"` // default 0
	Yanked        bool                   `protobuf:"varint,4,opt,name=yanked,proto3" json:"yanked,omitempty"`
	Manifest      *DigestRef             `protobuf:"bytes,5,opt,name=manifest,proto3" json:"manifest,omitempty"`
	ReleasedAt    string                 `protobuf:"bytes,6,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"` // RFC 3339 UTC
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	NotesUrl      string                 `protobuf:"bytes,8,opt,name=notes_url,json=notesUrl,proto3" json:"notes_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionNode) Reset() {
	*x = VersionNode{}
	mi := &file_rup_v2_objects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionNode) ProtoMessage() {}

func (x *VersionNode) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionNode.ProtoReflect.Descriptor instead.
func (*VersionNode) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{3}
}

func (x *VersionNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionNode) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VersionNode) GetMinFrom() int64 {
	if x != nil {
		return x.MinFrom
	}
	return 0
}

func (x *VersionNode) GetYanked() bool {
	if x != nil {
		return x.Yanked
	}
	return false
}

func (x *VersionNode) GetManifest() *DigestRef {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *VersionNode) GetReleasedAt() string {
	if x != nil {
		return x.ReleasedAt
	}
	return ""
}

func (x *VersionNode) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *VersionNode) GetNotesUrl() string {
	if x != nil {
		return x.NotesUrl
	}
	return ""
}

// Index is the signed channel pointer (schema rup.index/2).
type Index struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Schema          string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "rup.index/2"
	Product         string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Channel         string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Sequence        int64                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`                             // >= 1
	GeneratedAt     string                 `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`     // RFC 3339 UTC
	MinSupported    int64                  `protobuf:"varint,6,opt,name=min_supported,json=minSupported,proto3" json:"min_supported,omitempty"` // 0 means unset / not enforced
	HasMinSupported bool                   `protobuf:"varint,7,opt,name=has_min_supported,json=hasMinSupported,proto3" json:"has_min_supported,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // optional RFC 3339
	Versions        []*VersionNode         `protobuf:"bytes,9,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_rup_v2_objects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{4}
}

func (x *Index) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Index) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Index) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Index) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Index) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *Index) GetMinSupported() int64 {
	if x != nil {
		return x.MinSupported
	}
	return 0
}

func (x *Index) GetHasMinSupported() bool {
	if x != nil {
		return x.HasMinSupported
	}
	return false
}

func (x *Index) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Index) GetVersions() []*VersionNode {
	if x != nil {
		return x.Versions
	}
	return nil
}

// Artifact describes one downloadable file inside a Manifest.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`           // archive|installer|binary|blob
	Selectors     []*Selector            `protobuf:"bytes,6,rep,name=selectors,proto3" json:"selectors,omitempty"` // sorted by key when encoded
	Urls          []string               `protobuf:"bytes,7,rep,name=urls,proto3" json:"urls,omitempty"`
	Meta          []*MetaEntry           `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty"` // sorted by key when encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_rup_v2_objects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Artifact) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *Artifact) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Artifact) GetMeta() []*MetaEntry {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Manifest describes all artifacts for one version (schema rup.manifest/2).
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "rup.manifest/2"
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Code          int64                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	ReleasedAt    string                 `protobuf:"bytes,5,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_rup_v2_objects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{6}
}

func (x *Manifest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Manifest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Manifest) GetReleasedAt() string {
	if x != nil {
		return x.ReleasedAt
	}
	return ""
}

func (x *Manifest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Manifest) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// StagedArtifact is local-only; never published with urls.
type StagedArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Selectors     []*Selector            `protobuf:"bytes,6,rep,name=selectors,proto3" json:"selectors,omitempty"`
	Meta          []*MetaEntry           `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty"`
	SourcePath    string                 `protobuf:"bytes,8,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"` // discarded at publish
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StagedArtifact) Reset() {
	*x = StagedArtifact{}
	mi := &file_rup_v2_objects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedArtifact) ProtoMessage() {}

func (x *StagedArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedArtifact.ProtoReflect.Descriptor instead.
func (*StagedArtifact) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{7}
}

func (x *StagedArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StagedArtifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StagedArtifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StagedArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *StagedArtifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StagedArtifact) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *StagedArtifact) GetMeta() []*MetaEntry {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StagedArtifact) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

// Staged is the offline stage product (schema rup.staged/2).
type Staged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "rup.staged/2"
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Code          int64                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	MinFrom       int64                  `protobuf:"varint,5,opt,name=min_from,json=minFrom,proto3" json:"min_from,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	Artifacts     []*StagedArtifact      `protobuf:"bytes,9,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staged) Reset() {
	*x = Staged{}
	mi := &file_rup_v2_objects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staged) ProtoMessage() {}

func (x *Staged) ProtoReflect() protoreflect.Message {
	mi := &file_rup_v2_objects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staged.ProtoReflect.Descriptor instead.
func (*Staged) Descriptor() ([]byte, []int) {
	return file_rup_v2_objects_proto_rawDescGZIP(), []int{8}
}

func (x *Staged) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Staged) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Staged) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Staged) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Staged) GetMinFrom() int64 {
	if x != nil {
		return x.MinFrom
	}
	return 0
}

func (x *Staged) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Staged) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Staged) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Staged) GetArtifacts() []*StagedArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

var File_rup_v2_objects_proto protoreflect.FileDescriptor

const file_rup_v2_objects_proto_rawDesc = "" +
	"\n" +
	"\x14rup/v2/objects.proto\x12\x06rup.v2\"2\n" +
	"\bSelector\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"K\n" +
	"\tDigestRef\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls\"\xf1\x01\n" +
	"\vVersionNode\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x19\n" +
	"\bmin_from\x18\x03 \x01(\x03R\aminFrom\x12\x16\n" +
	"\x06yanked\x18\x04 \x01(\bR\x06yanked\x12-\n" +
	"\bmanifest\x18\x05 \x01(\v2\x11.rup.v2.DigestRefR\bmanifest\x12\x1f\n" +
	"\vreleased_at\x18\x06 \x01(\tR\n" +
	"releasedAt\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12\x1b\n" +
	"\tnotes_url\x18\b \x01(\tR\bnotesUrl\"\xb3\x02\n" +
	"\x05Index\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\tR\vgeneratedAt\x12#\n" +
	"\rmin_supported\x18\x06 \x01(\x03R\fminSupported\x12*\n" +
	"\x11has_min_supported\x18\a \x01(\bR\x0fhasMinSupported\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12/\n" +
	"\bversions\x18\t \x03(\v2\x13.rup.v2.VersionNodeR\bversions\"\xe1\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12.\n" +
	"\tselectors\x18\x06 \x03(\v2\x10.rup.v2.SelectorR\tselectors\x12\x12\n" +
	"\x04urls\x18\a \x03(\tR\x04urls\x12%\n" +
	"\x04meta\x18\b \x03(\v2\x11.rup.v2.MetaEntryR\x04meta\"\xd1\x01\n" +
	"\bManifest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x03R\x04code\x12\x1f\n" +
	"\vreleased_at\x18\x05 \x01(\tR\n" +
	"releasedAt\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12.\n" +
	"\tartifacts\x18\a \x03(\v2\x10.rup.v2.ArtifactR\tartifacts\"\xf4\x01\n" +
	"\x0eStagedArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12.\n" +
	"\tselectors\x18\x06 \x03(\v2\x10.rup.v2.SelectorR\tselectors\x12%\n" +
	"\x04meta\x18\a \x03(\v2\x11.rup.v2.MetaEntryR\x04meta\x12\x1f\n" +
	"\vsource_path\x18\b \x01(\tR\n" +
	"sourcePath\"\x88\x02\n" +
	"\x06Staged\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x03R\x04code\x12\x19\n" +
	"\bmin_from\x18\x05 \x01(\x03R\aminFrom\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x124\n" +
	"\tartifacts\x18\t \x03(\v2\x16.rup.v2.StagedArtifactR\tartifactsB\x82\x01\n" +
	"\n" +
	"com.rup.v2B\fObjectsProtoP\x01Z-github.com/shichao402/relkit/api/rup/v2;rupv2\xa2\x02\x03RXX\xaa\x02\x06Rup.V2\xca\x02\x06Rup\\V2\xe2\x02\x12Rup\\V2\\GPBMetadata\xea\x02\aRup::V2b\x06proto3"

var (
	file_rup_v2_objects_proto_rawDescOnce sync.Once
	file_rup_v2_objects_proto_rawDescData []byte
)

func file_rup_v2_objects_proto_rawDescGZIP() []byte {
	file_rup_v2_objects_proto_rawDescOnce.Do(func() {
		file_rup_v2_objects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rup_v2_objects_proto_rawDesc), len(file_rup_v2_objects_proto_rawDesc)))
	})
	return file_rup_v2_objects_proto_rawDescData
}

var file_rup_v2_objects_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rup_v2_objects_proto_goTypes = []any{
	(*Selector)(nil),       // 0: rup.v2.Selector
	(*MetaEntry)(nil),      // 1: rup.v2.MetaEntry
	(*DigestRef)(nil),      // 2: rup.v2.DigestRef
	(*VersionNode)(nil),    // 3: rup.v2.VersionNode
	(*Index)(nil),          // 4: rup.v2.Index
	(*Artifact)(nil),       // 5: rup.v2.Artifact
	(*Manifest)(nil),       // 6: rup.v2.Manifest
	(*StagedArtifact)(nil), // 7: rup.v2.StagedArtifact
	(*Staged)(nil),         // 8: rup.v2.Staged
}
var file_rup_v2_objects_proto_depIdxs = []int32{
	2, // 0: rup.v2.VersionNode.manifest:type_name -> rup.v2.DigestRef
	3, // 1: rup.v2.Index.versions:type_name -> rup.v2.VersionNode
	0, // 2: rup.v2.Artifact.selectors:type_name -> rup.v2.Selector
	1, // 3: rup.v2.Artifact.meta:type_name -> rup.v2.MetaEntry
	5, // 4: rup.v2.Manifest.artifacts:type_name -> rup.v2.Artifact
	0, // 5: rup.v2.StagedArtifact.selectors:type_name -> rup.v2.Selector
	1, // 6: rup.v2.StagedArtifact.meta:type_name -> rup.v2.MetaEntry
	7, // 7: rup.v2.Staged.artifacts:type_name -> rup.v2.StagedArtifact
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_rup_v2_objects_proto_init() }
func file_rup_v2_objects_proto_init() {
	if File_rup_v2_objects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rup_v2_objects_proto_rawDesc), len(file_rup_v2_objects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rup_v2_objects_proto_goTypes,
		DependencyIndexes: file_rup_v2_objects_proto_depIdxs,
		MessageInfos:      file_rup_v2_objects_proto_msgTypes,
	}.Build()
	File_rup_v2_objects_proto = out.File
	file_rup_v2_objects_proto_goTypes = nil
	file_rup_v2_objects_proto_depIdxs = nil
}
