// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: updater/v1/payload.proto

package updaterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptPhase int32

const (
	ScriptPhase_SCRIPT_PHASE_UNSPECIFIED ScriptPhase = 0
	ScriptPhase_SCRIPT_PHASE_PRE_APPLY   ScriptPhase = 1
	ScriptPhase_SCRIPT_PHASE_POST_APPLY  ScriptPhase = 2
)

// Enum value maps for ScriptPhase.
var (
	ScriptPhase_name = map[int32]string{
		0: "SCRIPT_PHASE_UNSPECIFIED",
		1: "SCRIPT_PHASE_PRE_APPLY",
		2: "SCRIPT_PHASE_POST_APPLY",
	}
	ScriptPhase_value = map[string]int32{
		"SCRIPT_PHASE_UNSPECIFIED": 0,
		"SCRIPT_PHASE_PRE_APPLY":   1,
		"SCRIPT_PHASE_POST_APPLY":  2,
	}
)

func (x ScriptPhase) Enum() *ScriptPhase {
	p := new(ScriptPhase)
	*p = x
	return p
}

func (x ScriptPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_updater_v1_payload_proto_enumTypes[0].Descriptor()
}

func (ScriptPhase) Type() protoreflect.EnumType {
	return &file_updater_v1_payload_proto_enumTypes[0]
}

func (x ScriptPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptPhase.Descriptor instead.
func (ScriptPhase) EnumDescriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{0}
}

type ScriptInterpreter int32

const (
	ScriptInterpreter_SCRIPT_INTERPRETER_UNSPECIFIED ScriptInterpreter = 0
	ScriptInterpreter_SCRIPT_INTERPRETER_DIRECT      ScriptInterpreter = 1
	ScriptInterpreter_SCRIPT_INTERPRETER_SH          ScriptInterpreter = 2
	ScriptInterpreter_SCRIPT_INTERPRETER_POWERSHELL  ScriptInterpreter = 3
)

// Enum value maps for ScriptInterpreter.
var (
	ScriptInterpreter_name = map[int32]string{
		0: "SCRIPT_INTERPRETER_UNSPECIFIED",
		1: "SCRIPT_INTERPRETER_DIRECT",
		2: "SCRIPT_INTERPRETER_SH",
		3: "SCRIPT_INTERPRETER_POWERSHELL",
	}
	ScriptInterpreter_value = map[string]int32{
		"SCRIPT_INTERPRETER_UNSPECIFIED": 0,
		"SCRIPT_INTERPRETER_DIRECT":      1,
		"SCRIPT_INTERPRETER_SH":          2,
		"SCRIPT_INTERPRETER_POWERSHELL":  3,
	}
)

func (x ScriptInterpreter) Enum() *ScriptInterpreter {
	p := new(ScriptInterpreter)
	*p = x
	return p
}

func (x ScriptInterpreter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptInterpreter) Descriptor() protoreflect.EnumDescriptor {
	return file_updater_v1_payload_proto_enumTypes[1].Descriptor()
}

func (ScriptInterpreter) Type() protoreflect.EnumType {
	return &file_updater_v1_payload_proto_enumTypes[1]
}

func (x ScriptInterpreter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptInterpreter.Descriptor instead.
func (ScriptInterpreter) EnumDescriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{1}
}

// FileTable is stored as files.pb at the root of a payload artifact.
// It is the complete set of files owned by this release. Deletions are derived
// by comparing this table with the last successfully applied baseline.
type FileTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "relkit.payload/1"
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Scripts       []*ScriptEntry         `protobuf:"bytes,3,rep,name=scripts,proto3" json:"scripts,omitempty"`
	Preserve      []string               `protobuf:"bytes,4,rep,name=preserve,proto3" json:"preserve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTable) Reset() {
	*x = FileTable{}
	mi := &file_updater_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTable) ProtoMessage() {}

func (x *FileTable) ProtoReflect() protoreflect.Message {
	mi := &file_updater_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTable.ProtoReflect.Descriptor instead.
func (*FileTable) Descriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *FileTable) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *FileTable) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileTable) GetScripts() []*ScriptEntry {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *FileTable) GetPreserve() []string {
	if x != nil {
		return x.Preserve
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relpath       string                 `protobuf:"bytes,1,opt,name=relpath,proto3" json:"relpath,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"` // 64 lowercase hex chars
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`    // portable permission bits; 0 means use 0644
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_updater_v1_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_updater_v1_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{1}
}

func (x *FileEntry) GetRelpath() string {
	if x != nil {
		return x.Relpath
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ScriptEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         ScriptPhase            `protobuf:"varint,1,opt,name=phase,proto3,enum=relkit.updater.v1.ScriptPhase" json:"phase,omitempty"`
	Relpath       string                 `protobuf:"bytes,2,opt,name=relpath,proto3" json:"relpath,omitempty"` // relative to scripts/
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Interpreter   ScriptInterpreter      `protobuf:"varint,6,opt,name=interpreter,proto3,enum=relkit.updater.v1.ScriptInterpreter" json:"interpreter,omitempty"`
	Args          []string               `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptEntry) Reset() {
	*x = ScriptEntry{}
	mi := &file_updater_v1_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptEntry) ProtoMessage() {}

func (x *ScriptEntry) ProtoReflect() protoreflect.Message {
	mi := &file_updater_v1_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptEntry.ProtoReflect.Descriptor instead.
func (*ScriptEntry) Descriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{2}
}

func (x *ScriptEntry) GetPhase() ScriptPhase {
	if x != nil {
		return x.Phase
	}
	return ScriptPhase_SCRIPT_PHASE_UNSPECIFIED
}

func (x *ScriptEntry) GetRelpath() string {
	if x != nil {
		return x.Relpath
	}
	return ""
}

func (x *ScriptEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScriptEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ScriptEntry) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ScriptEntry) GetInterpreter() ScriptInterpreter {
	if x != nil {
		return x.Interpreter
	}
	return ScriptInterpreter_SCRIPT_INTERPRETER_UNSPECIFIED
}

func (x *ScriptEntry) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Baseline is local engine state and is never published.
type Baseline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // must be "relkit.baseline/1"
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Files         []*BaselineEntry       `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baseline) Reset() {
	*x = Baseline{}
	mi := &file_updater_v1_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baseline) ProtoMessage() {}

func (x *Baseline) ProtoReflect() protoreflect.Message {
	mi := &file_updater_v1_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baseline.ProtoReflect.Descriptor instead.
func (*Baseline) Descriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{3}
}

func (x *Baseline) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Baseline) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Baseline) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Baseline) GetFiles() []*BaselineEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type BaselineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relpath       string                 `protobuf:"bytes,1,opt,name=relpath,proto3" json:"relpath,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineEntry) Reset() {
	*x = BaselineEntry{}
	mi := &file_updater_v1_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineEntry) ProtoMessage() {}

func (x *BaselineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_updater_v1_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineEntry.ProtoReflect.Descriptor instead.
func (*BaselineEntry) Descriptor() ([]byte, []int) {
	return file_updater_v1_payload_proto_rawDescGZIP(), []int{4}
}

func (x *BaselineEntry) GetRelpath() string {
	if x != nil {
		return x.Relpath
	}
	return ""
}

func (x *BaselineEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_updater_v1_payload_proto protoreflect.FileDescriptor

const file_updater_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x18updater/v1/payload.proto\x12\x11relkit.updater.v1\x1a\x1egoogle/protobuf/duration.proto\"\xad\x01\n" +
	"\tFileTable\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x122\n" +
	"\x05files\x18\x02 \x03(\v2\x1c.relkit.updater.v1.FileEntryR\x05files\x128\n" +
	"\ascripts\x18\x03 \x03(\v2\x1e.relkit.updater.v1.ScriptEntryR\ascripts\x12\x1a\n" +
	"\bpreserve\x18\x04 \x03(\tR\bpreserve\"e\n" +
	"\tFileEntry\x12\x18\n" +
	"\arelpath\x18\x01 \x01(\tR\arelpath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"\x9a\x02\n" +
	"\vScriptEntry\x124\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1e.relkit.updater.v1.ScriptPhaseR\x05phase\x12\x18\n" +
	"\arelpath\x18\x02 \x01(\tR\arelpath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12F\n" +
	"\vinterpreter\x18\x06 \x01(\x0e2$.relkit.updater.v1.ScriptInterpreterR\vinterpreter\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\"\x88\x01\n" +
	"\bBaseline\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x126\n" +
	"\x05files\x18\x04 \x03(\v2 .relkit.updater.v1.BaselineEntryR\x05files\"A\n" +
	"\rBaselineEntry\x12\x18\n" +
	"\arelpath\x18\x01 \x01(\tR\arelpath\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256*d\n" +
	"\vScriptPhase\x12\x1c\n" +
	"\x18SCRIPT_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SCRIPT_PHASE_PRE_APPLY\x10\x01\x12\x1b\n" +
	"\x17SCRIPT_PHASE_POST_APPLY\x10\x02*\x94\x01\n" +
	"\x11ScriptInterpreter\x12\"\n" +
	"\x1eSCRIPT_INTERPRETER_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SCRIPT_INTERPRETER_DIRECT\x10\x01\x12\x19\n" +
	"\x15SCRIPT_INTERPRETER_SH\x10\x02\x12!\n" +
	"\x1dSCRIPT_INTERPRETER_POWERSHELL\x10\x03B\xbc\x01\n" +
	"\x15com.relkit.updater.v1B\fPayloadProtoP\x01Z/go.firoyang.com/relkit/api/updater/v1;updaterv1\xa2\x02\x03RUX\xaa\x02\x11Relkit.Updater.V1\xca\x02\x11Relkit\\Updater\\V1\xe2\x02\x1dRelkit\\Updater\\V1\\GPBMetadata\xea\x02\x13Relkit::Updater::V1b\x06proto3"

var (
	file_updater_v1_payload_proto_rawDescOnce sync.Once
	file_updater_v1_payload_proto_rawDescData []byte
)

func file_updater_v1_payload_proto_rawDescGZIP() []byte {
	file_updater_v1_payload_proto_rawDescOnce.Do(func() {
		file_updater_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updater_v1_payload_proto_rawDesc), len(file_updater_v1_payload_proto_rawDesc)))
	})
	return file_updater_v1_payload_proto_rawDescData
}

var file_updater_v1_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_updater_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_updater_v1_payload_proto_goTypes = []any{
	(ScriptPhase)(0),            // 0: relkit.updater.v1.ScriptPhase
	(ScriptInterpreter)(0),      // 1: relkit.updater.v1.ScriptInterpreter
	(*FileTable)(nil),           // 2: relkit.updater.v1.FileTable
	(*FileEntry)(nil),           // 3: relkit.updater.v1.FileEntry
	(*ScriptEntry)(nil),         // 4: relkit.updater.v1.ScriptEntry
	(*Baseline)(nil),            // 5: relkit.updater.v1.Baseline
	(*BaselineEntry)(nil),       // 6: relkit.updater.v1.BaselineEntry
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_updater_v1_payload_proto_depIdxs = []int32{
	3, // 0: relkit.updater.v1.FileTable.files:type_name -> relkit.updater.v1.FileEntry
	4, // 1: relkit.updater.v1.FileTable.scripts:type_name -> relkit.updater.v1.ScriptEntry
	0, // 2: relkit.updater.v1.ScriptEntry.phase:type_name -> relkit.updater.v1.ScriptPhase
	7, // 3: relkit.updater.v1.ScriptEntry.timeout:type_name -> google.protobuf.Duration
	1, // 4: relkit.updater.v1.ScriptEntry.interpreter:type_name -> relkit.updater.v1.ScriptInterpreter
	6, // 5: relkit.updater.v1.Baseline.files:type_name -> relkit.updater.v1.BaselineEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_updater_v1_payload_proto_init() }
func file_updater_v1_payload_proto_init() {
	if File_updater_v1_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updater_v1_payload_proto_rawDesc), len(file_updater_v1_payload_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updater_v1_payload_proto_goTypes,
		DependencyIndexes: file_updater_v1_payload_proto_depIdxs,
		EnumInfos:         file_updater_v1_payload_proto_enumTypes,
		MessageInfos:      file_updater_v1_payload_proto_msgTypes,
	}.Build()
	File_updater_v1_payload_proto = out.File
	file_updater_v1_payload_proto_goTypes = nil
	file_updater_v1_payload_proto_depIdxs = nil
}
