// Code generated by relkit-facade-gen. DO NOT EDIT.

package updaterfacade

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sync"
	"time"

	updaterv1 "firoyang.com/relkit/api/updater/v1"
	"firoyang.com/relkit/internal/updater"
)

// Glue locates and runs the sidecar. Hosts may inject a fake in tests.
type Glue interface {
	Locate(runtime *updaterv1.Runtime) (string, error)
	Run(ctx context.Context, bin string, args []string, stdin []byte, onEvent func(*updaterv1.UpdaterEvent)) error
}

// DefaultGlue implements the locked search order and stdio framing.
type DefaultGlue struct{}

func (DefaultGlue) Locate(rt *updaterv1.Runtime) (string, error) {
	name := "relkit-updater"
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	var candidates []string
	if rt != nil && rt.SidecarPath != "" {
		candidates = append(candidates, rt.SidecarPath)
	}
	if env := os.Getenv("RELKIT_UPDATER"); env != "" {
		candidates = append(candidates, env)
	}
	if rt != nil && rt.Install != nil && rt.Install.InstallRoot != "" {
		candidates = append(candidates, filepath.Join(rt.Install.InstallRoot, name))
	}
	if exe, err := os.Executable(); err == nil {
		candidates = append(candidates, filepath.Join(filepath.Dir(exe), name))
	}
	if rt != nil && rt.Install != nil && rt.Install.SidecarRelpath != "" && rt.Install.InstallRoot != "" {
		candidates = append(candidates, filepath.Join(rt.Install.InstallRoot, filepath.FromSlash(rt.Install.SidecarRelpath)))
	}
	for _, c := range candidates {
		if st, err := os.Stat(c); err == nil && !st.IsDir() {
			return c, nil
		}
	}
	return "", fmt.Errorf("sidecar not found")
}

func (DefaultGlue) Run(ctx context.Context, bin string, args []string, stdin []byte, onEvent func(*updaterv1.UpdaterEvent)) error {
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Stdin = bytes.NewReader(stdin)
	cmd.Stderr = os.Stderr
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}
	for {
		ev := &updaterv1.UpdaterEvent{}
		if err := updater.ReadFrame(stdout, ev); err != nil {
			break
		}
		if onEvent != nil {
			onEvent(ev)
		}
	}
	return cmd.Wait()
}

type Updater struct {
	profile *updaterv1.ClientProfile
	runtime *updaterv1.Runtime
	glue    Glue
	bin     string
	caps    *updaterv1.Capabilities
	mu      sync.Mutex
	cancel  context.CancelFunc
}

type OpenResult struct {
	Kind         string
	Updater      *Updater
	Capabilities *updaterv1.Capabilities
	Error        *updaterv1.Error
}

func Open(ctx context.Context, profile *updaterv1.ClientProfile, rt *updaterv1.Runtime, glue Glue) *OpenResult {
	if glue == nil {
		glue = DefaultGlue{}
	}
	bin, err := glue.Locate(rt)
	if err != nil {
		return &OpenResult{Kind: "failed", Error: &updaterv1.Error{
			Code:    updaterv1.ErrorCode_ERROR_CODE_SIDECAR_NOT_FOUND,
			Message: err.Error(),
		}}
	}
	u := &Updater{profile: profile, runtime: rt, glue: glue, bin: bin}
	caps, ferr := u.handshake(ctx)
	if ferr != nil {
		return &OpenResult{Kind: "failed", Error: ferr}
	}
	u.caps = caps
	return &OpenResult{Kind: "opened", Updater: u, Capabilities: caps}
}

func (u *Updater) handshake(ctx context.Context) (*updaterv1.Capabilities, *updaterv1.Error) {
	var caps *updaterv1.Capabilities
	var ferr *updaterv1.Error
	err := u.glue.Run(ctx, u.bin, []string{"-capabilities"}, nil, func(ev *updaterv1.UpdaterEvent) {
		if ev.GetCapabilities() != nil {
			caps = ev.GetCapabilities()
		}
		if ev.GetFailed() != nil {
			ferr = ev.GetFailed().GetError()
		}
	})
	if ferr != nil {
		return nil, ferr
	}
	if err != nil {
		return nil, &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_SIDECAR_NOT_FOUND, Message: err.Error(), Retryable: true}
	}
	if caps == nil {
		return nil, &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_PROTOCOL_MISMATCH, Message: "no capabilities"}
	}
	if caps.Ipc < IPCMin {
		return nil, &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_UPDATER_TOO_OLD, Message: "sidecar IPC too old"}
	}
	if caps.Ipc > IPCMax {
		return nil, &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_UPDATER_TOO_NEW, Message: "sidecar IPC too new"}
	}
	return caps, nil
}

func (u *Updater) call(ctx context.Context, req *updaterv1.UpdaterRequest, onEvent func(*updaterv1.UpdaterEvent)) []*updaterv1.UpdaterEvent {
	req.Hello = &updaterv1.ClientHello{IpcMin: IPCMin, IpcMax: IPCMax}
	req.Profile = u.profile
	req.Runtime = u.runtime
	raw, err := protoMarshal(req)
	if err != nil {
		return []*updaterv1.UpdaterEvent{failEvent(updaterv1.ErrorCode_ERROR_CODE_PROFILE_INVALID, err.Error())}
	}
	var events []*updaterv1.UpdaterEvent
	runErr := u.glue.Run(ctx, u.bin, nil, raw, func(ev *updaterv1.UpdaterEvent) {
		events = append(events, ev)
		if onEvent != nil {
			onEvent(ev)
		}
	})
	if runErr != nil && len(events) == 0 {
		return []*updaterv1.UpdaterEvent{failEvent(updaterv1.ErrorCode_ERROR_CODE_NETWORK, runErr.Error())}
	}
	return events
}

func protoMarshal(m *updaterv1.UpdaterRequest) ([]byte, error) {
	var buf bytes.Buffer
	if err := updater.WriteFrame(&buf, m); err != nil {
		return nil, err
	}
	// Engine reads one framed request from stdin; WriteFrame already framed it.
	return buf.Bytes(), nil
}

func failEvent(code updaterv1.ErrorCode, msg string) *updaterv1.UpdaterEvent {
	return &updaterv1.UpdaterEvent{Kind: &updaterv1.UpdaterEvent_Failed{Failed: &updaterv1.Failed{
		Error: &updaterv1.Error{Code: code, Message: msg},
	}}}
}

func (u *Updater) Capabilities() *updaterv1.Capabilities { return u.caps }

func (u *Updater) Check(ctx context.Context, force bool, exactCode int64, policy *updaterv1.CheckPolicy) *updaterv1.CheckResult {
	evs := u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Check{Check: &updaterv1.CheckOp{
		Force: force, ExactCode: exactCode, Policy: policy,
	}}}, nil)
	for _, ev := range evs {
		if ev.GetCheck() != nil {
			return ev.GetCheck()
		}
		if ev.GetFailed() != nil {
			return &updaterv1.CheckResult{Kind: &updaterv1.CheckResult_Failed{Failed: ev.GetFailed()}}
		}
	}
	return &updaterv1.CheckResult{Kind: &updaterv1.CheckResult_Failed{Failed: &updaterv1.Failed{
		Error: &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_NETWORK, Message: "no check result"},
	}}}
}

func (u *Updater) Skip(ctx context.Context, code int64) *updaterv1.Result {
	return lastResult(u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Skip{Skip: &updaterv1.SkipOp{Code: code}}}, nil))
}

func (u *Updater) Download(ctx context.Context, planId string, onEvent func(*updaterv1.UpdaterEvent)) *updaterv1.DownloadResult {
	evs := u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Download{Download: &updaterv1.DownloadOp{PlanId: planId}}}, onEvent)
	for _, ev := range evs {
		if ev.GetDownload() != nil {
			return ev.GetDownload()
		}
		if ev.GetFailed() != nil {
			return &updaterv1.DownloadResult{Kind: &updaterv1.DownloadResult_Failed{Failed: ev.GetFailed()}}
		}
	}
	return &updaterv1.DownloadResult{Kind: &updaterv1.DownloadResult_Failed{Failed: &updaterv1.Failed{
		Error: &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_NETWORK, Message: "no download result"},
	}}}
}

func (u *Updater) Apply(ctx context.Context, planId string, onEvent func(*updaterv1.UpdaterEvent)) *updaterv1.ApplyResult {
	evs := u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Apply{Apply: &updaterv1.ApplyOp{PlanId: planId}}}, onEvent)
	for _, ev := range evs {
		if ev.GetApply() != nil {
			return ev.GetApply()
		}
		if ev.GetFailed() != nil {
			return &updaterv1.ApplyResult{Kind: &updaterv1.ApplyResult_Failed{Failed: ev.GetFailed()}}
		}
	}
	return &updaterv1.ApplyResult{Kind: &updaterv1.ApplyResult_Failed{Failed: &updaterv1.Failed{
		Error: &updaterv1.Error{Code: updaterv1.ErrorCode_ERROR_CODE_NETWORK, Message: "no apply result"},
	}}}
}

func (u *Updater) Status(ctx context.Context) *updaterv1.StatusSnapshot {
	evs := u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Status{Status: &updaterv1.StatusOp{}}}, nil)
	for _, ev := range evs {
		if ev.GetStatus() != nil {
			return ev.GetStatus()
		}
	}
	return &updaterv1.StatusSnapshot{}
}

func (u *Updater) Cleanup(ctx context.Context) *updaterv1.Result {
	return lastResult(u.call(ctx, &updaterv1.UpdaterRequest{Op: &updaterv1.UpdaterRequest_Cleanup{Cleanup: &updaterv1.CleanupOp{}}}, nil))
}

func (u *Updater) Cancel() *updaterv1.Result {
	u.mu.Lock()
	defer u.mu.Unlock()
	if u.cancel != nil {
		u.cancel()
	}
	return &updaterv1.Result{Kind: &updaterv1.Result_Ok{Ok: &updaterv1.Ok{}}}
}

func lastResult(evs []*updaterv1.UpdaterEvent) *updaterv1.Result {
	for _, ev := range evs {
		if ev.GetResult() != nil {
			return ev.GetResult()
		}
		if ev.GetFailed() != nil {
			return &updaterv1.Result{Kind: &updaterv1.Result_Failed{Failed: ev.GetFailed()}}
		}
	}
	return &updaterv1.Result{Kind: &updaterv1.Result_Ok{Ok: &updaterv1.Ok{}}}
}

type Scheduler struct {
	u       *Updater
	cfg     *updaterv1.SchedulerConfig
	onEvent func(*SchedulerEvent)
	stop    chan struct{}
	running bool
	mu      sync.Mutex
}

type SchedulerEvent struct {
	Kind   string // tick | result
	At     time.Time
	Force  bool
	Result *updaterv1.CheckResult
}

func (u *Updater) Scheduler(cfg *updaterv1.SchedulerConfig, onEvent func(*SchedulerEvent)) *Scheduler {
	if cfg == nil {
		cfg = &updaterv1.SchedulerConfig{CheckOnStart: true, ForceOnStart: true}
	}
	return &Scheduler{u: u, cfg: cfg, onEvent: onEvent, stop: make(chan struct{})}
}

func (s *Scheduler) Start() *updaterv1.Result {
	s.mu.Lock()
	if s.running {
		s.mu.Unlock()
		return &updaterv1.Result{Kind: &updaterv1.Result_Ok{Ok: &updaterv1.Ok{}}}
	}
	s.running = true
	s.stop = make(chan struct{})
	s.mu.Unlock()
	go s.loop()
	return &updaterv1.Result{Kind: &updaterv1.Result_Ok{Ok: &updaterv1.Ok{}}}
}

func (s *Scheduler) Stop() *updaterv1.Result {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.running {
		close(s.stop)
		s.running = false
	}
	return &updaterv1.Result{Kind: &updaterv1.Result_Ok{Ok: &updaterv1.Ok{}}}
}

func (s *Scheduler) IsRunning() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.running
}

func (s *Scheduler) loop() {
	first := true
	for {
		force := false
		if first {
			if !s.cfg.CheckOnStart {
				first = false
			} else {
				force = s.cfg.ForceOnStart
			}
		}
		if first && s.cfg.CheckOnStart {
			s.tick(force)
			first = false
		}
		wait := updaterMinWait(s.cfg.Policy)
		timer := time.NewTimer(wait)
		select {
		case <-s.stop:
			timer.Stop()
			return
		case <-timer.C:
			s.tick(false)
		}
	}
}

func (s *Scheduler) tick(force bool) {
	if s.onEvent != nil {
		s.onEvent(&SchedulerEvent{Kind: "tick", At: time.Now(), Force: force})
	}
	res := s.u.Check(context.Background(), force, 0, s.cfg.Policy)
	if s.onEvent != nil {
		s.onEvent(&SchedulerEvent{Kind: "result", At: time.Now(), Force: force, Result: res})
	}
}

func updaterMinWait(p *updaterv1.CheckPolicy) time.Duration {
	s, f := time.Hour*24, time.Hour
	if p != nil {
		if p.AfterSuccess != nil && p.AfterSuccess.AsDuration() > 0 {
			s = p.AfterSuccess.AsDuration()
		}
		if p.AfterFailure != nil && p.AfterFailure.AsDuration() > 0 {
			f = p.AfterFailure.AsDuration()
		}
	}
	if s < 5*time.Minute {
		s = 5 * time.Minute
	}
	if f < 5*time.Minute {
		f = 5 * time.Minute
	}
	if f < s {
		return f
	}
	return s
}
